FROM node:16-alpine AS build
ARG _ENV
WORKDIR /app
COPY . /app
COPY .env.$_ENV .env

RUN npm install --legacy-peer-deps
RUN if [ "$_ENV" = "production" ]; then \
      npm run build-prod; \
    else \
      npm run build; \
    fi
FROM nginx:alpine as production
WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build app/dist/ /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]