FROM php:8.3

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    nano apt-utils openssl zip unzip git libfreetype6-dev \
    libjpeg62-turbo-dev libpng-dev libzip-dev libonig-dev curl \
    libxml2-dev libmagickwand-dev imagemagick build-essential && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm && \
    docker-php-ext-install gd zip xml simplexml iconv pdo pdo_mysql mysqli && \
    docker-php-ext-configure zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY ./composer.json /app
RUN composer install; exit 0

COPY . /app
RUN npm install  --legacy-peer-deps
RUN npm run build

RUN composer update

RUN #php artisan key:generate
RUN php artisan storage:link
RUN npm run build

CMD php artisan serve --host=0.0.0.0 --port=8181
EXPOSE 8181
RUN php artisan cache:clear